### ISSUE TITLE
Cannot parse type for talent 730 (group 7)

### ISSUE THREAD

**Issue by seriaati** [seriaati/genshin.py#105]
Sentry issue: https://seria-ati.sentry.io/share/issue/dc9d5bb136304541bd596c8f34001900/
Ashlen says it's caused by Dendro traveler, idk.

**Comment by ashleney** [comment]
It turns out that from what I can see in `AvatarSkillExcelConfigData` the traveler talents are not at all consistent. Due to some characters having more passives than others, it's also practically impossible to judge their types by order alone. I highly recommend referring to static game data if the type is essential.

Otherwise, you can just assume the first 3 `character.talents` are upgradeable unless the 3rd one is a dash.

**Comment by seriaati** [comment]
Understood.
> Otherwise, you can just assume the first 3 character.talents are upgradeable unless the 3rd one is a dash.
Yeah, but is there a way to automate the process of recognizing whether it is a dash or not? Currently I just hard code the talent ID of ayaka's and mona's dash

**Comment by ashleney** [comment]
> Yeah, but is there a way to automate the process of recognizing whether it is a dash or not? Currently I just hard code the talent ID of ayaka's and mona's dash

Might as well add it I suppose.
