### ISSUE TITLE
Add star rail battle chronicle

### ISSUE THREAD

**Issue by ashleney** [seriaati/genshin.py#115]
Seems only CN has this for now. 

See [hewang1an/StarRail-plugin](https://github.com/hewang1an/StarRail-plugin)

**Comment by BobbyWibowo** [comment]
Hey there, just a heads up that Global has this now

It seems quite similar to Genshin's Battle Chronicles 

https://www.hoyolab.com/article/19152801/?lang=en-us&utm_source=sns&utm_medium=link

CC @EffortlessFury too, since you were the one that got the daily check-ins working

---

It seems we will also get an equivalent of Genshin's Traveler's Diary, named Trailblaze Monthly Calendar, on 16 June
