### ISSUE TITLE
api don't send full character list per user

### ISSUE THREAD

**Issue by ar1ls** [seriaati/genshin.py#14]
![image](https://user-images.githubusercontent.com/85633875/151198666-830975f5-9527-4d03-8c06-f58bfac2e2c3.png)
![image](https://user-images.githubusercontent.com/85633875/151198725-2919b8f4-4f9d-4f0c-9cd4-6107708b1519.png)
api send 8 characters but user have more char 
![image](https://user-images.githubusercontent.com/85633875/151198985-5b9f60fe-42de-4dae-bc20-8a0dd78561a3.png)

**Comment by ashleney** [comment]
That's expected behavior. Mihoyo has limited the number of visible characters to only 8. You look at [this post](https://www.hoyolab.com/article/2002956) to see how to change them (this feature will be implemented soon).

This change has most likely been caused by sites like [spiralabyss.org](https://spiralabyss.org/) completely abusing the API and making huge batches of requests towards Mihoyo's servers. We will have to wait for an official announcement explaining the situation I suppose.

**Comment by ar1ls** [comment]
ok, thx
