### ISSUE TITLE
Generic exception raised from `_get_db_char` is difficult to handle

### ISSUE THREAD

**Issue by luoshuijs** [seriaati/genshin.py#68]
We were seeing this exception being thrown a few times:

https://github.com/thesadru/genshin.py/blob/99a6a41277ddd68edb1c5b7ff2cd3606d2249d37/genshin/models/genshin/character.py#L55-L57

Our hope is to be able to gracefully handle the specific exception, for instance:

```python
try:
    # load character
except LanguageNotFound as lang_exc:
    # log and handle error (update from enka)
    log.error(f"language {lang_exc.lang} not found")
```

without having to catch the generic `Exception` (which could be any other error types).

It'll be really helpful to us if we have something similar to a `LanguageNotFound` to catch and handle.

And of course, thank you for maintaining this great project.

**Comment by ashleney** [comment]
I think it would be easier to just update the characters right at launch. Since you only need to run one of the update_character functions once it shouldn't be a problem.

I can consider making this an error once I implement a persistent cache, currently it's way too abstracted to warrant an error.

Also I swear I made it so it's run automatically anyways for any chronicle endpoints, what endpoint gives this warning?

**Comment by luoshuijs** [comment]
We're currently not able to reproduce the problem - but the main concern is failing upon initialization may prevent our bot from successfully starting.

After giving it more thoughts, this is actually a non-issue. We can handle the rare edge cases of init failure on our side (likely due to network issues, in which case the service would've failed anyways).

Thanks for the prompt response. Closing as this is not an issue
